[package]
name = "mask"
version = "0.0.1"
authors = ["John Weachock <jweachock@gmail.com>"]

[dependencies]
bincode = "1.0.0"
blake2 = "0.7.1"
clap = "2.30.0"
codemap = "0.1.1"
gc = "0.3.2"
gc_derive = "0.3.2"
ordered-float = "0.5.0"
serde = "1.0.42"
serde_derive = "1.0.42"
serde_yaml = "0.7.4"
