use lexer::Token;

#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub enum Instr {
  BinOp(Token),
  Block(Vec<Instr>),
  Break,
  Call,
  CmpOp(Token, bool),
  Continue,
  Dup,
  ForBreak,
  FuncDef(Vec<Instr>),
  Get,
  If(Vec<Instr>),
  IfElse(Vec<Instr>, Vec<Instr>),
  Instr,
  Jump(isize),
  LogicOp(Token),
  MethodGet,
  NewTable,
  Nop,
  Pop,
  Print,
  PushConst(usize),
  PushScope,
  Return,
  Returnable(Vec<Instr>),
  Set,
  Truthy,
  Nully,
  UnOp(Token),
  Loop(Vec<Instr>),
}
